[package]
name = "lumina"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
bincode_derive = "2.0.1"
burn = { version = "0.17.0", features = ["vision", "train", "tch", "fusion"] }
image = "0.25.6"
